name: Run Tests

on:
  pull_request:
    branches: [ main ]  # or 'master' depending on your default branch
  push:
    branches: [ main ]  # this will also run tests on direct pushes to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'  # Specify your Python version

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python3-pyaudio

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Add any other test dependencies you need
        pip install -e .  # Install your package in editable mode

    - name: Run tests
      run: |
        pytest
